/**
 * constants-template.ts
 *
 * Template for the project's constants.ts — the central data hub.
 * All scripts (generate-tts, rebuild-timeline, style-scan) read from this file.
 *
 * Copy this template into your composition directory and customize:
 *   src/<CompositionName>/constants.ts
 */

import { loadFont } from "@remotion/google-fonts/NotoSansSC";
import { loadFont as loadInter } from "@remotion/google-fonts/Inter";

// Font loading — call with NO arguments to load all subsets.
// Do NOT pass subsets: ["chinese-simplified"] — Remotion v4 uses
// Unicode range numbers as subset names, not human-readable names.
const { fontFamily: notoSansSC } = loadFont();
const { fontFamily: inter } = loadInter();

export const FONTS = { notoSansSC, inter };

// ---------------------------------------------------------------------------
// Color Palette
// ---------------------------------------------------------------------------

export const COLORS = {
  background: {
    dark: "#1a1a2e", // Deep space blue — default background
    medium: "#16213e", // Medium blue — secondary backgrounds
    light: "#0f3460", // Lighter blue — highlights
  },
  accent: {
    rose: "#e94560", // Warm accent — important elements
    yellow: "#f9ed69", // Bright accent — highlights
    teal: "#00b8a9", // Cool accent — secondary info
  },
  text: "#ffffff",
  textMuted: "#b0b0b0",

  // Scene-level backgrounds (optional, see style-guide.md § Scene-Level Palette Variation)
  sceneBg: {
    space: ["#0a0a1a", "#1a1a2e"],
    ocean: ["#0a1628", "#0f3460"],
    biology: ["#1a2e1a", "#163e2e"],
    energy: ["#2e1a1a", "#3e1621"],
    tech: ["#1a1a2e", "#16213e"],
  },
};

// ---------------------------------------------------------------------------
// Scene Timeline
// ---------------------------------------------------------------------------
// Keys must match NARRATION keys below.
// Phase 4: use estimated durations. Phase 4.5: rebuild-timeline.ts overwrites.

export const SCENES = {
  hook: { start: 0, duration: 150 },
  concept: { start: 150, duration: 300 },
  summary: { start: 450, duration: 120 },
} as const;

export const TRANSITION_DURATION = 20;

export const TOTAL_FRAMES = 570;

// ---------------------------------------------------------------------------
// Narration Text (source for TTS)
// ---------------------------------------------------------------------------
// Keys should match SCENES keys. Values are the FULL spoken text.
// generate-tts.ts extracts text from this object and auto-splits into segments.

export const NARRATION = {
  hook: "你有没有想过，为什么天空是蓝色的？",
  concept:
    "秘密要从阳光说起。阳光看起来是白色的，但其实它包含了所有颜色。当阳光进入大气层，蓝色光因为波长短，更容易被空气分子散射到各个方向。",
  summary: "所以我们看到的蓝天，就是散射的蓝色光。",
} as const;

// ---------------------------------------------------------------------------
// Audio Segments (auto-generated by rebuild-timeline.ts)
// ---------------------------------------------------------------------------
// Phase 4: Use estimated timing below. Phase 4.5: rebuild-timeline.ts --write
// will overwrite this entire block with real durations from TTS audio files.

export const AUDIO_SEGMENTS = {
  hook: [
    {
      text: "你有没有想过",
      file: "hook-seg00.mp3",
      startFrame: 15,
      endFrame: 50,
    },
    {
      text: "为什么天空是蓝色的",
      file: "hook-seg01.mp3",
      startFrame: 55,
      endFrame: 110,
    },
  ],
  concept: [
    {
      text: "秘密要从阳光说起",
      file: "concept-seg00.mp3",
      startFrame: 165,
      endFrame: 210,
    },
    // ... more segments
  ],
  summary: [
    {
      text: "所以我们看到的蓝天",
      file: "summary-seg00.mp3",
      startFrame: 465,
      endFrame: 510,
    },
    {
      text: "就是散射的蓝色光",
      file: "summary-seg01.mp3",
      startFrame: 515,
      endFrame: 555,
    },
  ],
} as const;
